[package]
name = "gridworld_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
neural_network = { path = "../neural_network" }
genetic_algorithm = { path = "../genetic_algorithm" }
gridworld = { path = "../gridworld" }
rand = "0.8"
ndarray = "0.16.1"
macroquad = "0.4.13"